# Generated by Django 3.2 on 2021-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210521_2058'),
        ('users', '0006_auto_20210521_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='related_user', to='orders.Order', verbose_name='Заказы пользователя'),
        ),
    ]
