version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: bash -c "
       chmod +x ./wait-for-it.sh && 
       ./wait-for-it.sh &&              
       python ./web_store/manage.py makemigrations &&
       python ./web_store/manage.py migrate &&       
       python ./web_store/manage.py loaddata ./web_store/web_store/fixtures/initial_data.json &&       
       python ./web_store/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db