# Generated by Django 3.1.7 on 2021-04-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import first_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Category')),
                ('image', models.ImageField(default='default_img.jpg', upload_to='', verbose_name='Изображение')),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=50)),
                ('email_is_verifyed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(default='Some description ...', max_length=255, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=9)),
                ('amount', models.PositiveIntegerField(default=5, validators=[first_app.models.validate_amount_of_product])),
                ('image', models.ImageField(default='default_img.jpg', upload_to='', verbose_name='Изображение')),
                ('slug', models.SlugField(default='', editable=False, unique=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.category')),
            ],
        ),
    ]
