# Generated by Django 3.2 on 2021-05-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_for_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Для анонимного пользователя'),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_in_order_process',
            field=models.BooleanField(default=False, verbose_name='В процессе заказа'),
        ),
    ]
