# Generated by Django 3.2 on 2021-05-21 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210521_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ready_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Время готовности'),
        ),
    ]
